### ISSUE TITLE
Jail image dimensions read to document root

### ISSUE THREAD

**Issue by gocom** [textile/php-textile#145]
Currently you can read any image's dimensions. This essentially allows scanning the servers' file structure. 

Might be good idea to rename doc_root to something else too.

**Comment by netcarver** [comment]
@gocom I've started work on this and pushed it up as branch [issue-145](https://github.com/textile/php-textile/tree/issue-145) for you to look at.

**Comment by philwareham** [comment]
Not sure where Gocom is right now. I will check this for you within next couple if days

**Comment by netcarver** [comment]
@philwareham, @gocom I intend to merge this in the next day or so for the upcoming 3.6.0 release.

**Comment by philwareham** [comment]
Great, I'll roll the new version into our Textpattern 4.7 developments. Cheers!

**Comment by netcarver** [comment]
@philwareham I've merged this into master on my local environment - let's see what travis makes of the tests when I push it up. :)

**Comment by netcarver** [comment]
@philwareham Here's the [release](https://github.com/textile/php-textile/releases/tag/v3.6.0).

**Comment by philwareham** [comment]
Thanks, I've dropped it into my local Textpattern dev and it seems to work without error so far, will continue testing.

You might want to update your license dates at it still shows 2013.

**Comment by netcarver** [comment]
Done, thanks @philwareham.

**Comment by philwareham** [comment]
Putting my pedantic hat on, Jukka made commits in 2014. `DataBag.php` and `Tag.php` still show a copyright of 2014 which you might want to update too. :)
